stages:
  - Building
  - Deployment

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: Building
  services:
    - docker:dind
  before_script:
    - echo $CI_DOCKERHUB_PASSWORD | docker login -u "$CI_DOCKERHUB_USER" --password-stdin $CI_DOCKERHUB_REGISTRY
  script:
    - docker build --pull -t "index.docker.io/tbcp/debian" .
    - docker push "index.docker.io/tbcp/debian"
  only:
    - main

docker-build-develop:
  # Official docker image.
  image: docker:latest
  stage: Building
  services:
    - docker:dind
  before_script:
    - echo $CI_DOCKERHUB_PASSWORD | docker login -u "$CI_DOCKERHUB_USER" --password-stdin $CI_DOCKERHUB_REGISTRY
  script:
    - docker build --pull -t "index.docker.io/tbcp/debian:develop" .
    - docker push "index.docker.io/tbcp/debian:develop"
  only:
    - develop

docker-build:
  # Official docker image.
  image: docker:latest
  stage: Building
  services:
    - docker:dind
  before_script:
    - echo $CI_DOCKERHUB_PASSWORD | docker login -u "$CI_DOCKERHUB_USER" --password-stdin $CI_DOCKERHUB_REGISTRY
  script:
    - docker build --pull -t "index.docker.io/tbcp/debian:latest" .
    - docker push "index.docker.io/tbcp/debian:latest"
  except:
    - main
    - develop

pages:
    stage: Deployment
    script:
        - mkdir ./public
        - cp -r README.md public/ && cp -r USAGE.md public/
    artifacts:
        paths: [public]
        expire_in: 1 mins
